name: Build and Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Assicurati che corrisponda al nome della tua branch principale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'  # Assicurati che corrisponda alla versione di Node.js usata nel tuo progetto
    - run: npm install
    - run: npm run build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
